name: Typst Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Setup Typst
        uses: typst-community/setup-typst@v5

      - name: Ensure yq is available
        run: |
          if ! command -v yq &> /dev/null; then
            sudo wget -qO /usr/local/bin/yq \
              https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
          fi

      - name: Prepare metadata.yml
        env:
          CV_NAME:              ${{ secrets.CV_NAME }}
          CV_EMAIL:             ${{ secrets.CV_EMAIL }}
          CV_PHONE:             ${{ secrets.CV_PHONE }}
          CV_LOCATION:          ${{ secrets.CV_LOCATION }}
          CV_GITHUB_USERNAME:   ${{ secrets.CV_GITHUB_USERNAME }}
          CV_LINKEDIN_USERNAME: ${{ secrets.CV_LINKEDIN_USERNAME }}
          CV_WEBSITE:           ${{ secrets.CV_WEBSITE }}
        run: |
          mv example.metadata.yml metadata.yml

          yq -i '
            .name             = strenv(CV_NAME)              |
            .email            = strenv(CV_EMAIL)             |
            .phone            = strenv(CV_PHONE)             |
            .location         = strenv(CV_LOCATION)          |
            .githubUsername   = strenv(CV_GITHUB_USERNAME)   |
            .linkedinUsername = strenv(CV_LINKEDIN_USERNAME) |
            .website          = strenv(CV_WEBSITE)
          ' metadata.yml

      - name: Compile Typst to PDF
        if: success()
        run: typst c main.typ Chandrashekhar_Resume.pdf

      - name: Check output (after rename)
        run: ls

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: Chandrashekhar_Resume.pdf

      - name: Notify if CV was compiled successfully
        if: success()
        run: |
          curl \
            -H $"Title: CV ${{ github.ref_name }} published successfully" \
            -H "X-Tags: memo, CV, version-update, updated-link" \
            -H "Content-Type: text/plain" \
            -d $'CV ${{ github.ref_name }} published successfully.\nYou can find the updated CV at https://github.com/cr2007/CV/releases/latest/download/Chandrashekhar_Resume.pdf\nStatus: ${{job.status}}' \
            ${{ vars.NTFY_GACTIONS_URL }}

      - name: Removes older releases
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          keep-count: 3
          keep-old-minor-releases: false
